name: warden
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
   path: ^1.8.0
   watcher: ^1.1.1
   ansicolor: ^2.0.1
   args: ^2.4.2
   yaml: ^3.1.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

