name: warden
description: Static Builder CLI
version: 0.8.2
repository: https://github.com/joegasewicz/warden
homepage: https://github.com/joegasewicz/warden
environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  warden: warden

dependencies:
   path: ^1.8.0
   watcher: ^1.1.1
   args: ^2.4.2
   yaml: ^3.1.1
   logging: ^1.3.0
   ansi_styles: ^0.3.2+1
   cli_spinner: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
